TOKEN_REFRESH_MARGIN_SECONDS = 5 * 60
MAX_TOKEN_LIFETIME_SECONDS = 24 * 60 * 60

PLAYBACK_MINIMUM_TOKEN_SECONDS = 55 * 60
EXPORT_MINIMUM_TOKEN_SECONDS = PLAYBACK_MINIMUM_TOKEN_SECONDS

FOLDER_CACHE_TTL_SECONDS = 3 * 60
FOLDER_CACHE_MAX_ENTRIES = 50
FOLDER_CACHE_MAX_BYTES = 2 * 1024 * 1024
